### ISSUE TITLE
Could not find the input file when running the program during hardware emulation

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#149]
I used absolute path when I created my host program as show below:
![image](https://user-images.githubusercontent.com/71826731/148512871-8d4141c5-f614-41a6-8008-094407c79c25.png)
But when running the program using "./app.exe" during hw_emu, it displayed as show below:
![5688338d5064821ca24b756dd4be1a0](https://user-images.githubusercontent.com/71826731/148513084-50d74f22-d77f-497a-a6ac-58dbb0ccfbef.png)

Does anyone know why?
Thank you!

**Comment by imrickysu** [comment]
Hi @Candice-Yin , please provide evidences that these files exist in your emulation environment.

Please note that these files should be in your rootfs, not on your x86 host machine because hardware emulation cannot access x86 filesystem.

It's better to add your files in sd_dir so that these files can be packaged into FAT32 partition of sd_card.img. These data files will be in the same directory as your app.exe in /media/sd-mmcblk0p1.

For more info about sd_dir, please refer to https://github.com/Xilinx/Vitis-Tutorials/blob/2021.2/Vitis_Platform_Creation/Introduction/02-Edge-AI-ZCU104/step3.md

**Comment by Candice-Yin** [comment]
Thank you @imrickysu I solved it. 
I‘m not sure about one thing: how can I connect the data files that host progam reads with the input data that the source code for the kernel needs? By the same  name of variables?

**Comment by imrickysu** [comment]
Sure. I'm closing this issue.

For the question about feeding data to kernel, please read docs about your kernel API. Data in user space and kernel space are separated. It needs one data copy to send data from user space to kernel space, or use kernel API to allocate memory space and fill in data to the data pointer.
