### ISSUE TITLE
Kernel Panic: Unable to handle kernel paging request at virtual address

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#171]
Hi, I completed hw_emu successfully. But when I ran the accelerated application on the ZCU102, I met an error:
![e7ee019126a9317ca376f62ed206f05](https://user-images.githubusercontent.com/71826731/150138445-3b92d0d3-60ef-44e6-a228-483a8cd0f3ee.png)
@imrickysu Thank you.

**Comment by imrickysu** [comment]
Hi @Candice-Yin , from the kernel panic message, it looks like to be related to Ethernet driver (macb) during moving data (dma). It's hard to say whether the issue comes from driver code or application code. But if you have network data movement in your application, please try remove them and only deal with local data first. Please let me know if this error still happens when dealing with local data. We can do more analysis.
