### ISSUE TITLE
AIEngineDevelopment Example 01 -- Issues in compiling

### ISSUE THREAD

**Issue by TizianoDeMatteis** [Xilinx/Vitis-Tutorials#259]
Hello, 

I'm trying to compile the `01-aie_lenet_tutorial` (v 2022.1) using the `vck19_base_202210_1` platform, but I'm encountering some issues.
I'm following the step-by-step guide (so making the kernels, the graph, xclbin...), targeting HW_EMU.

The environment has been set up according to the instruction in the README (after that I edited the `env_setup.sh` file indicating the location of versal common files).

Steps:
- the commands `make kernel` and `make graph` complete without any error
- the `make xclbin` target _does not exist_. Instead, I've used the `make xsa` target, which seems the closest one in terms of commands
- the `make application` target fails. At first, it complains about not finding some libraries:
    ```
    /home/tdematt/versal_software/Vitis-Tutorials/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial/design/host_app_src/lenet_app.cpp:27:10: fatal error: xrt/experimental/xrt_aie.h: No such file or directory
   27 | #include "xrt/experimental/xrt_aie.h"
    ```
    Then, after inspecting the command being executed I noticed that:
    - this is using `g++` and not `aarch64-linux-gnu-g++` as indicated in the README (https://github.com/Xilinx/Vitis-Tutorials/tree/2022.1/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial#make-application-compile-the-host-application)
    - if I want to use the explicit compilation commands shown in the README, this is using some environment variables (e.g., `XILINX_VITIS_AIETOOLS`) that have been not set up by your configuration file, and paths that are wrong (e.g., I don't have at this point any directory `build/Work`)
    
Could be something wrong with my configuration?
If yes, any help in fixing this is appreciated.

Thanks

**Comment by xflorentw** [comment]
Hi @TizianoDeMatteis 
So the first issue with make xsa -> make xclbin should be fixed in the README file.

For the second issue, make sure you are editing the following script for your environment and running it before running the make command
https://github.com/Xilinx/Vitis-Tutorials/blob/2022.1/AI_Engine_Development/Design_Tutorials/01-aie_lenet_tutorial/sample_env_setup.sh

Make sure you check the output of this script because I know the following line is only giving a warning if you have a the LD_LIBRARY env. variable set but this is not setting environment correctly
source $XILINX_VERSAL/environment-setup-cortexa72-cortexa53-xilinx-linux

So you need to make sure the environment variable is unset before running the script

**Comment by TizianoDeMatteis** [comment]
Hi @xflorentw,

> Make sure you check the output of this script because I know the following line is only giving a warning if you have a the LD_LIBRARY env. variable set but this is not setting environment correctly
source $XILINX_VERSAL/environment-setup-cortexa72-cortexa53-xilinx-linux

Yes, this was indeed the case, I missed the warning message.
Once, I fixed it, the compilation proceeded smoothly

**Comment by xflorentw** [comment]
Great. Can you kindly close the issue as this is solved?
Thanks

**Comment by TizianoDeMatteis** [comment]
Yes,
this solved the issue.
Thank you for your support.
