### ISSUE TITLE
HwAcc/Intro: Vitis_Library source code not found during compilation

### ISSUE THREAD

**Issue by AnusheelXilinx** [Xilinx/Vitis-Tutorials#273]
https://github.com/Xilinx/Vitis-Tutorials/blob/2022.1/Hardware_Acceleration/Introduction/guided_sw_examples.md 

The tutorial does not take care of Vitis_Libraries and the flow is failing with below error:
ERROR: [v++ 207-812] 'common/xf_common.hpp' file not found (/scratch/anusheel/Alveo_Intro/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/resize_rgb.cpp:32:10)
ERROR: [v++ 60-300] Failed to build kernel(ip) resize_accel_rgb, see log for details: /scratch/anusheel/Alveo_Intro/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log
ERROR: [v++ 60-773] In '/scratch/anusheel/Alveo_Intro/Vitis-Tutorials/Hardware_Acceleration/Introduction/design_source/hw_src/_x/resize_rgb/resize_accel_rgb/vitis_hls.log', caught Tcl error: ERROR: [HLS 207-812] 'common/xf_common.hpp' file

**Comment by imrickysu** [comment]
We removed the Vitis_Libraries as submodule of the whole repo because only a small subset of the tutorials refer to Vitis-Libraries.
Each referring tutorials should take care of dependencies individually. 
Please add dependency check and git clone accordingly in Makfile. Hardware_Acceleration/Introduction/design_source/hw_src/Makefile

Example: https://github.com/Xilinx/Vitis-Tutorials/blob/ce34ef8cd5204ff0e52d81891bc96ab8f4ba4a60/Vitis_Platform_Creation/Design_Tutorials/02-Edge-AI-ZCU104/ref_files/step3_validate/Makefile#L34

**Comment by AnusheelXilinx** [comment]
Closing the thread as there are no open concerns.

Thanks
Anusheel
