### ISSUE TITLE
"std_abs.h:52:11: error: ‘::abs’ has not been declared" during sw_emu

### ISSUE THREAD

**Issue by Candice-Yin** [Xilinx/Vitis-Tutorials#309]
![image](https://user-images.githubusercontent.com/71826731/194837462-8820a130-c280-41e6-a7ec-152c674186dd.png)
How can I solve this problem?
Thanks very much.

**Comment by imrickysu** [comment]
Hi @Candice-Yin , do you mean this error occurs only when running sw-emu, but not happen on hw or hw-emu? Please confirm.

According to the resources from Internet, this seems to be a generic C++ host code issue. https://stackoverflow.com/questions/62541664/abs-was-not-declared-in-this-scope. 

If this issue is related to any specific tutorials, we can continue to discuss here. If not, please visit forums.xilinx.com and the question in Xilinx forums. There will be more engineers helping you there.
