### ISSUE TITLE
Vitis-Tutorials/Vitis_HLS/Design_Tutorials /02-Beamformer/ERROR: [HLS 200-101] add_files: Too many positional arguments specified.

### ISSUE THREAD

**Issue by praphull4** [Xilinx/Vitis-Tutorials#448]
I am getting error **ERROR: [HLS 200-101] add_files: Too many positional arguments specified**, while following the initial 6 steps of _https://github.com/Xilinx/Vitis-Tutorials/tree/2023.2/Vitis_HLS/Design_Tutorials/02-Beamformer#results_ in **Vitis HLS 2023.2.**

I have assigned the project name as mgs_qrd_wbs_usplus.
Added` ./reference_files/mgs_qrd_wbs.cpp` and `./reference_files/mgs_qrd_wbs.h` as a Design File, .`/reference_files/mgs_qrd_wbs_tb.cpp `as a Test Bench File, set the Top Function to `mgs_qrd.`

Please give the solution for **Vitis HLS 2023.2**

**Comment by praphull4** [comment]
I was able to run simulation and synthesis using Vitis Unified IDE. But similar Read.Md can be created for Vitis HLS as well.

**Comment by allyzhou** [comment]
@praphull4   I can run C sim and synth without any error in Vitis IDE or CLI and in both 2023.2 and 2024.1. by Vitis HLS, do you mean the Classic Vitis HLS? Please note since 2023.2, Vitis Unified IDE has become the default GUI of Vitis (including HLS) and that's what was used to create this tutorial. the Classic IDE will soon be deprecated.

**Comment by AnusheelXilinx** [comment]
Closing the issue as there are no further concerns.
